---
- name: Get VirtualBox version.
  shell: cat /home/vagrant/.vbox_version
  register: result

- set_fact: virtualbox_version={{ result.stdout }}

- name: Mount VirtualBox guest additions ISO.
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version }}.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: Run VirtualBox guest additions installation.
  shell: sh /tmp/vbox/VBoxLinuxAdditions.run
  failed_when: false

- name: Unmount VirtualBox guest additions ISO.
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version }}.iso"
    state: absent
    fstype: iso9660

- name: Delete VirtualBox guest additions ISO.
  file:
    path: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version }}.iso"
    state: absent
